function results = myimfcn(im)
%Image Processing Function
%
% IM      - Input image.
% RESULTS - A scalar structure with the processing results.
%Please open imageBatchProcessor App and run this code.

%--------------------------------------------------------------------------
% Auto-generated by imageBatchProcessor App. 
%
% When used by the App, this function will be called for every input image
% file automatically. IM contains the input image as a matrix. RESULTS is a
% scalar structure containing the results of this processing function.
%
%--------------------------------------------------------------------------



% image resizing 227 by 2227 pixels----------------------------------

im=imresize(im,[224,224]);
results=im;

%--------------------------------------------------------------------------
